spring.application.name=BlogOnline





spring.security.oauth2.client.registration.github.client-id=${clientIdGithub}
spring.security.oauth2.client.registration.github.client-secret=${clientSecretGithub}

#Configuraciones de OAuth con Google
spring.security.oauth2.client.registration.google.client-id=${clientIdGoogle}
spring.security.oauth2.client.registration.google.client-secret=${clientSecretGoogle}


security.jwt.private.key=${privateKeyJWT}
security.jwt.user.generator=${userGeneratorJWT}



spring.datasource.url=${dbUrl}
spring.datasource.username=${dbUsername}
spring.datasource.password=${dbPassword}


spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect




